export const ANTIALERGICOS = [
    {
        id: 1,
        nome:"Cloridatro de ambroxol",
        imagem:"antialergico1.png",
        descricao:"Para Alivia a Tosse",
        preco:"5,00 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"10",
        receitamento: false
    },
    {
        id: 2,
        nome:"Cloradatro",
        imagem:"antialergico2.png",
        descricao:"Para Espirros, Coriza",
        preco:"10,00 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"10",
        receitamento: false
    },
    {
        id: 3,
        nome:"Alergomine",
        imagem:"antialergico3.png",
        descricao:"Para rinite",
        preco:"9,99 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"20",
        receitamento: false
    },
    {
        id: 4,
        nome:"Refenax",
        imagem:"antialergico4.png",
        descricao:"Contém Loratadina",
        preco:"18,98 R$",
        tipoProduto:"Medicamento Manipulado",
        qtdComprimidos:"Líquido 100ml",
        receitamento: true
    },
    {
        id: 5,
        nome:"Antialergico na WEB",
        imagem:"antialergico5.png",
        descricao:"Para sinusites",
        preco:"16,00 R$",
        tipoProduto:"Medicamento Manipulado",
        qtdComprimidos:"Liquido 50ml",
        receitamento: true
    },
    
]
export const ANALGESICOS = [
    {
        id: 1,
        nome:"Dorflex",
        imagem:"analgesicos1.png",
        descricao:"Para Enxaquecas",
        preco:"9,99 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"10",
        receitamento: false
    },
    {
        id: 2,
        nome:"Dorflex",
        imagem:"analgesicos2.png",
        descricao:"Relaxante Muscular",
        preco:"45,62 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"30",
        receitamento: false
    },
    {
        id: 3,
        nome:"Ibuprofeno",
        imagem:"analgesicos3.png",
        descricao:"Alivio da dor e febre",
        preco:"17,99 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"20",
        receitamento: false
    },
    {
        id: 4,
        nome:"Novalgina",
        imagem:"analgesicos4.png",
        descricao:"Dipirona Monoidratada",
        preco:"12,35 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"15",
        receitamento: false
    },
    {
        id: 5,
        nome:"Torsilax",
        imagem:"analgesicos5.png",
        descricao:"Uso oral",
        preco:"24,00 R$",
        tipoProduto:"Medicamento Genérico",
        qtdComprimidos:"25",
        receitamento: false
    },
]
export const INFANTIL = [
    {
        id: 1,
        nome:"Mamadeira",
        imagem:"infantil1.png",
        descricao: "De 0 a 6 meses",
        preco:"22,50 R$",
        tipoProduto:"Para recém nascidos",
        qtdUnidade:"1",
    },
    {
        id: 2,
        nome:"Fralda Huggies",
        imagem:"infantil2.png",
        descricao:"Fralda, tamanho M",
        preco:"68,00 R$",
        tipoProduto:"Uso único",
        qtdUnidade:"88/1",
    },
    {
        id: 3,
        nome:"Lenços Umedecidos",
        imagem:"infantil3.png",
        descricao:"Lenços Umedecidos",
        preco:"9,99 R$",
        tipoProduto:"Uso único",
        qtdUnidade:"48/1",
    },
    {
        id: 4,
        nome:"Leite em pó Ninho",
        imagem:"infantil4.png",
        descricao:"Composto lácteo",
        preco:"44,50 R$",
        tipoProduto:"Nutritivo",
        qtdUnidade:"750 g",
    },
    {
        id: 5,
        nome:"Chupeta",
        imagem:"infantil5.png",
        descricao:"100% soft",
        preco:"20,00 R$",
        tipoProduto:"De 1 a 2 anos",
        qtdUnidade:"1",
    },
]
export const PERFUMES = [
    {
        id: 1,
        nome:"Perfume Paco Rabanne",
        imagem:"perfumes1.png",
        descricao:"Contém 200ml",
        preco:"550,00 R$",
        tipoProduto:"Masculino",
        qtdUnidade:"1",
    },
    {
        id: 2,
        nome:"Perfume La Vie Est Belle Oui",
        imagem:"perfumes2.png",
        descricao:"Feminino, contém 50ml",
        preco:"648,99 R$",
        tipoProduto:"Feminino",
        qtdUnidade:"1",
    },
    {
        id: 3,
        nome:"Dior J'ADORE LUMIÈRE",
        imagem:"perfumes3.jpg",
        descricao:"Feminino, contém 50ml",
        preco:"400,50 R$",
        tipoProduto:"Feminino",
        qtdUnidade:"1",
    },
    {
        id: 4,
        nome:"Paco Rabanne Night",
        imagem:"perfumee4.png",
        descricao:"Masculino, 50ml",
        preco:"599,99 R$",
        tipoProduto:"Masculino",
        qtdUnidade:"1",
    },
    {
        id: 5,
        nome:"Paco Rabanne Her",
        imagem:"perfumes5.png",
        descricao:"Feminino, 50ml",
        preco:"845,94 R$",
        tipoProduto:"Feminino",
        qtdUnidade:"1",
    },
]
export const COSMETICOS = [
    {
        id: 1,
        nome:"Nivea Men Care",
        imagem:"cosmeticos1.png",
        descricao:"Shampoo Masculino, 200ml",
        preco:"29,58 R$",
        tipoProduto:"Shampoo",
        qtdUnidade:"1",
    },
    {
        id: 2,
        nome:"Dove Secrets",
        imagem:"cosmeticos2.png",
        descricao:"Shampoo Feminino, 200ml",
        preco:"29,58 R$",
        tipoProduto:"Shampoo",
        qtdUnidade:"1",
    },
    {
        id: 3,
        nome:"Máscara Capilar",
        imagem:"cosmeticos3.png",
        descricao:"DaBelle, 800G",
        preco:"15,00 R$",
        tipoProduto:"Restaurador",
        qtdUnidade:"1",
    },
    {
        id: 4,
        nome:"Kit Capilar",
        imagem:"cosmeticos4.png",
        descricao:"Niely Gold",
        preco:"35,00 R$",
        tipoProduto:"Shampoo e Condicionador",
        qtdUnidade:"2",
    },
    {
        id: 5,
        nome:"Finalizador",
        imagem:"cosmeticos5.png",
        descricao:"Da TRESemmé",
        preco:"7,48 R$",
        tipoProduto:"Para Cabelos",
        qtdUnidade:"1",
    },
]